baseURL = "https://keep9ing.github.io/"
languageCode = "ko-kr"
title = '기록하자 뭐든'
theme = "hugo-book"

buildDrafts = false
publishDir = "public"
cleanDestinationDir = true  # Hugo에서 제공하는 clean 옵션(깨끗한 빌드 보장)

[params]
  BookMenuBundle = "menu"
  BookSectionPagesMenu = false  # 자동 메뉴 생성 비활성화